# Generated by Django 4.2.5 on 2023-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluminium_price', models.FloatField()),
                ('pvc_futures_price', models.FloatField()),
                ('last_fetch_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AluminiumPrice',
        ),
        migrations.DeleteModel(
            name='PVCPrice',
        ),
    ]
