# Generated by Django 4.2.5 on 2023-10-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_stockprice_aluminium_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiumPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluminium_price', models.CharField(max_length=255)),
                ('last_fetch_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PVCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvc_futures_price', models.CharField(max_length=255)),
                ('last_fetch_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
