# Generated by Django 4.2.5 on 2023-10-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_aluminiumprice_pvcprice_delete_stockprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluminiumprice',
            old_name='last_fetch_datetime',
            new_name='last_time',
        ),
        migrations.RenameField(
            model_name='pvcprice',
            old_name='last_fetch_datetime',
            new_name='last_time',
        ),
    ]
